PERSONAS = [
    {"name": "Sarah",  "device": "mobile",  "customer_type": "first_time", "goal": "cheapest_plan"},
    {"name": "Alex",   "device": "desktop", "customer_type": "returning",  "goal": "renew"},
    {"name": "Taylor", "device": "mobile",  "customer_type": "returning",  "goal": "signup"},
    {"name": "Priya",  "device": "desktop", "customer_type": "first_time", "goal": "compare_plans"},
    {"name": "Jamie",  "device": "mobile",  "customer_type": "first_time", "goal": "signup"},
    {"name": "Elena",  "device": "desktop", "customer_type": "returning",  "goal": "renew"},
    {"name": "Marcus", "device": "mobile",  "customer_type": "returning",  "goal": "cheapest_plan"},
    {"name": "Devon",  "device": "desktop", "customer_type": "first_time", "goal": "signup"},
    {"name": "Noor",   "device": "mobile",  "customer_type": "first_time", "goal": "compare_plans"},
    {"name": "Ravi",   "device": "desktop", "customer_type": "returning",  "goal": "cheapest_plan"},
    {"name": "Casey",  "device": "mobile",  "customer_type": "returning",  "goal": "renew"},
    {"name": "Miriam", "device": "desktop", "customer_type": "first_time", "goal": "cheapest_plan"},
    {"name": "Liam",   "device": "mobile",  "customer_type": "first_time", "goal": "signup"},
    {"name": "Faith",  "device": "desktop", "customer_type": "returning",  "goal": "compare_plans"},
    {"name": "Kenji",  "device": "mobile",  "customer_type": "returning",  "goal": "signup"},
    {"name": "Amara",  "device": "desktop", "customer_type": "first_time", "goal": "renew"},
    {"name": "Owen",   "device": "mobile",  "customer_type": "first_time", "goal": "cheapest_plan"},
    {"name": "Yuki",   "device": "desktop", "customer_type": "returning",  "goal": "signup"},
    {"name": "Bianca", "device": "mobile",  "customer_type": "returning",  "goal": "compare_plans"},
    {"name": "Tomas",  "device": "desktop", "customer_type": "first_time", "goal": "cheapest_plan"},
]